# Generated by Django 5.0.6 on 2024-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='default-cover.jpeg', upload_to='bookss/image'),
        ),
    ]
