# Generated by Django 5.0.6 on 2024-06-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='default-cover.jpeg', upload_to=''),
        ),
    ]
