# Generated by Django 5.0.6 on 2024-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='start_given',
            new_name='stars_given',
        ),
    ]
